#!/usr/bin/env python3
from sys import argv
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

class ExitOnChange (FileSystemEventHandler):
    def on_any_event(self, event):
        exit()

if __name__ == "__main__":
    path = argv[1] if len(argv) > 1 else '.'
    event_handler = ExitOnChange()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    observer.join()
